"""init

Revision ID: c6a7c781b99b
Revises:
Create Date: 2020-02-21 13:17:06.550935

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision = "c6a7c781b99b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "series",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("episode", sa.Integer(), server_default="0", nullable=False),
        sa.Column("start", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sub_name", sa.String(length=50), server_default="", nullable=False),
        sa.PrimaryKeyConstraint("id", "source"),
    )
    op.create_index(op.f("ix_series_name"), "series", ["name"], unique=False)
    op.create_index(op.f("ix_series_source"), "series", ["source"], unique=False)
    op.create_index(op.f("ix_series_sub_name"), "series", ["sub_name"], unique=False)
    op.create_table(
        "subscription",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("episode", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "updating", sa.Boolean(), server_default=expression.false(), nullable=False
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscription")
    op.drop_index(op.f("ix_series_sub_name"), table_name="series")
    op.drop_index(op.f("ix_series_source"), table_name="series")
    op.drop_index(op.f("ix_series_name"), table_name="series")
    op.drop_table("series")
    # ### end Alembic commands ###
