# specific branch build with batching
trigger:
  branches:
    include:
      - "*"
    exclude:
      - "renovate/*"
  paths:
    include:
      - "*"
    exclude:
      - ".github/*"
      - "README.rst"
      - ".readthedocs.yml"
      - ".gitignore"
      - ".editorconfig"

schedules:
  - cron: "0 12 * * 6"
    displayName: Weekly Saturday build
    branches:
      include:
        - master
        - dev
    always: true

resources:
  repositories:
    - repository: trim21
      type: github
      endpoint: github
      # renovate: datasource=git-tags versioning=semver
      name: Trim21/azure-pipeline-templates
      ref: refs/tags/v0.0.5

stages:
  - stage: Lint
    jobs:
      - template: ./jobs/lint.yaml
  - stage: Test
    jobs:
      - template: ./jobs/unittest.yaml
