jobs:
  - template: /.ci/templates/job.yaml
    parameters:
      name: Test
      steps:
        - script: coverage run --source=bgmi -m pytest --junitxml tmp/junit/test_report.xml
          displayName: Unittest

        - bash: |
            bash <(curl -s https://codecov.io/bash) \
              -F "py_${PYV/./}" -F "os_${OS%'-latest'}" \
              -C "$(Build.SourceVersion)" \
              -B "${BUILD_SOURCEBRANCH#'refs/heads/'}"
          name: Codecov
          env:
            PYV: $(python_version)

        - task: PublishTestResults@2
          condition: succeededOrFailed()
          inputs:
            testResultsFiles: tmp/junit/test_*.xml
            testRunTitle: Publish test results for Python $(python_version)
