bgmi:
  output:
    aria2:
      url: http://127.0.0.1:6800/rpc
      secret: token:233
    notify:
      smtp:
        from: bgmi@trim21.me
        to: notify@trim21.me
        host: smtp.example.com
        port: 25
        password: 2333
        tls: true
