name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
      - uses: Trim21/setup-poetry@dist/v1

      - run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}

# create github release

      - name: Get Tag Name
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Install git-chglog
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          go get -u github.com/git-chglog/git-chglog/cmd/git-chglog

      - name: Generate Changlog
        run: |
          git-chglog "$TAG" | node -p 'require("fs").readFileSync(0).toString().trim()
            .split("\n").slice(1).join("\n").trim()' > chglog.md

      - name: Upload Github Release
        run: gh release create "$TAG" -F chglog.md ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
